apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    # Existing roles...
  mapUsers: |
    - userarn: arn:aws:iam::058264368002:user/eks
      username: eks
      groups:
        - system:masters
